dist: xenial
language: ruby
rvm:
  - 2.5.3
cache:
  - bundler
addons:
  postgresql: 9.5
  apt:
    packages:
      - libarchive-dev
services:
  - memcached
env:
  global:
    - OSM_MEMCACHE_SERVERS="127.0.0.1"
before_script:
  - cp config/travis.database.yml config/database.yml
  - cp config/example.storage.yml config/storage.yml
  - touch config/settings.local.yml
  - bundle exec rake db:create
  - psql -U postgres -c "CREATE EXTENSION btree_gist" openstreetmap
  - psql -U postgres -f db/functions/functions.sql openstreetmap
  - bundle exec rake db:migrate
  - bundle exec rake i18n:js:export
  - bundle exec rake yarn:install
script:
  - bundle exec rubocop -f fuubar
  - bundle exec rake eslint
  - bundle exec erblint .
  - bundle exec rake
